myproject/site/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, ValidationError, IntegerField
from wtforms.validators import DataRequired, Email, EqualTo

from flask_login import current_user
from myproject.models import Student 

class LoginForm(FlaskForm):
    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators = [DataRequired()])
    submit = SubmitField("Log in")

class RegistrationForm(FlaskForm):
    email = StringField("Email", validators = [DataRequired(), Email()])
    username = StringField('Username', validators = [DataRequired()])
    password = PasswordField('Password', validators = [DataRequired(), EqualTo('pass_confirm', message = 'Passwords must match')])
    pass_confirm = PasswordField('Confirm Password', validators = [DataRequired()])
    submit = SubmitField('Register!')

    def check_email(self, field):
        if Student.query.filter_by(email =  field.data).first():
            raise ValidationError("This email is already in use.")

    def check_username(self, field):
        if Student.query.filter_by(username =  field.data).first():
            raise ValidationError("This user name is already in use.")

class SettingsForm(FlaskForm):
    words_a_day = IntegerField("How many words would you like to learn a day?")
    submit = SubmitField('Ok')

myproject/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
import openai
import config

openai.api_key = config.api_key

login_manager  = LoginManager()

app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecretkey'
basedir = os.path.abspath(os.path.dirname(__file__))

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db  =SQLAlchemy(app)
Migrate(app,db)

#from myproject.api.views import api_blueprint
from myproject.site.views import site_blueprint

#app.register_blueprint(api_blueprint, url_prefix = '/api')
app.register_blueprint(site_blueprint, url_prefix = '/site')

login_manager.init_app(app)

login_manager.login_view = 'login'

def get_completion(prompt, model="gpt-3.5-turbo", temperature=0.6):
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=temperature, # this is the degree of randomness of the model's output
    )
    return response.choices[0].message["content"]

def use_word(word):
    prompt = f"""Use the word "{word}" as it appears in a short sentence.""".format(word.capitalize())
    return get_completion(prompt)

app.jinja_env.globals.update(use_word=use_word)

myproject/site/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, abort
from myproject import db, app
from myproject.site.forms import LoginForm, RegistrationForm, SettingsForm
from myproject.models import Student
from flask_login import login_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash

from flask_login import current_user


site_blueprint = Blueprint('site', __name__, template_folder = 'templates/site')

@site_blueprint.route('/')
def index():
    return "<h1>Welcome to the Home Page!</h1>"

@site_blueprint.route('/register', methods = ['GET','POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
       email = form.email.data
       username = form.username.data
       password = form.password.data
       new_student = Student(email, username, password)
       db.session.add(new_student)
       db.session.commit()
       return redirect(url_for('site.login'))
    return render_template('register.html', form = form)

# There's a better way to do this todays_list function.
# I could call the words directly from the dataframe in SQL.


#@site_blueprint.route('/register', methods = ['GET','POST'])
#def register():
#    form = RegistrationForm()
#
#    if form.validate_on_submit():
#        student = Student(email = form.email.data, username = form.username.data, password = form.password.data)
#        db.session.add(student)
#        db.session.commit()
#        flash("Thanks for registering!")
#        return redirect(url_for('site.login'))
#    return render_template('register.html', form=form)

@site_blueprint.route('/login', methods = ['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        student = Student.query.filter_by(email = form.email.data).first()

        if student.check_password(form.password.data) and student is not None:

            login_user(student, remember = True)
            flash('Log in successful')

            #Ok. Here is where we want to instantiate todays_list. Fingers crossed.
            current_user.todays_list_inst(current_user.words_a_day)

            # This is pretty cool.
            # It goes back and finds the page the user was looking for before
            # they logged in, retrieves is and sends the user there.
            next= request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('welcome_user')

            return redirect(next)
            #return render_template('welcome_user.html')

    return render_template('login.html', form = form)
    

@site_blueprint.route('/welcome')
@login_required
def welcome_user():
    return render_template('welcome_user.html')

@site_blueprint.route('/settings', methods = ['GET','POST'])
@login_required
def settings():
    form = SettingsForm()
    if form.validate_on_submit():
        student = Student.query.filter_by(username = current_user.username).first()
        new_words_a_day = form.words_a_day.data
        student.words_a_day = new_words_a_day
        #._get_current_object()
        db.session.add(student)
        db.session.commit()
        return redirect(url_for('site.todays_list'))

    return render_template('settings.html', form = form)

@site_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You Logged Out!')
    return redirect(url_for('index'))



@site_blueprint.route('/todays_list')
@login_required
def todays_list():
    todays_list = current_user.todays_list()
    return render_template('Todays_list.html', todays_list = todays_list)

@site_blueprint.route('/flashcards')
@login_required
def flashcards():
    #This is just a placeholder now. The cards don't do anything yet.
    todays_list = current_user.todays_list()
    return render_template('Flashcards.html', todays_list = todays_list)

@app.route('/welcome')
@login_required
def welcome_user():
    return render_template('welcome_user.html')

myproject/templates/base.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>ISEE Vocab Page</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class = "navbar-nav">
    <a class="nav-item nav-link"><a href="{{url_for('index')}}">Home</a>
    {% if current_user.is_authenticated %}
      <li class="nav-link"> <a href  = '{{url_for('site.logout')}}'>Log Out </a></li>
      <li class="nav-link"> <a href="{{url_for('site.settings')}}">Settings</a></li>
      <li class = "nav-link"> <a href="{{url_for('site.todays_list')}}">Today's Word List</a></li>
      <li class = "nav-link"> <a href="{{url_for('site.flashcards')}}">Flashcards</a></li>
    {% else%}
      <li class="nav-link"> <a href  = '{{url_for('site.login')}}'>Log In </a></li>
      <li class="nav-link"> <a href  = '{{url_for('site.register')}}'>Register </a></li>
    {% endif %}


  </div>
</nav>

    {% block content %}

    {% endblock %}
  </body>
</html>

myproject/templates/home.html
{% extends "base.html" %}

{% block content %}


<div class="jumbotron">

  {% if current_user.is_authenticated %}

  <h1>Welcome to the Praxis ISEE page.</h1>
  <h3>Menu Items:</h3>
  <ol>
    <li>Today's Card List: </li>
    <a href="#"></a>
    <li>Today's FC</li>
    <a href="#"></a>
    <li>Settings</li>
    <a href="#"></a>
  </ol>

  {% else %}

  <h1>Log in or register to start!</h1>

  {% endif %}



</div>



{% endblock %}